blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ HyperHDR Discussions
    url: https://github.com/awawa-dev/HyperHDR/discussions
    about: Ask questions, get help with configuration, or share your setup here!